rocketmq:
  accessKey: xxx
  accessSecret: xxx
  consumerGroup: fraud-detection
  topic: fraud-detection-transactions
  endpoints: rmq-cn-ow74af0r201-vpc.cn-guangzhou.rmq.aliyuncs.com:8080
  awaitDurationSeconds: 30

sls:
  accessKey: xxx
  accessSecret: xxx
  endpoint: cn-guangzhou-intranet.log.aliyuncs.com
  projectName: fraud-detection
  logStoreName: fraud-transaction-log
  producer:
    retries: 3
    baseRetryBackoffMs: 100
    maxRetryBackoffMs: 10000
    ioThreadCount: 64

fraudDetection:
  amountCheckRuleThreshold: 100000000
  suspiciousAccounts: 123,456,789
  # messageConsumer thread pool configs
  messageConsumerThreadPoolQueueSize: 1000
  messageConsumerCorePoolSize: 16
  messageConsumerMaxPoolSize: 32
  messageConsumerKeepAliveTimeSeconds: 60

logging:
  level:
    root: WARN
    com.hsbc: DEBUG
  file:
    name: /app/log/fraud-detection.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7